import React, { useState, useMemo } from "react";
import DATA from "./data/app-data.json";
import { Home, Shield, Users, CalendarDays, ChevronLeft, ChevronRight, Search, MoreHorizontal, Coffee, Github, FileText, Database } from "lucide-react";

// ============================================================================
// DATA — generated by scripts/build_data.py from the project CSVs.
// In the real app this arrives from /v1/* endpoints and is cached in IndexedDB.
// Compact array form to keep payload small: same shape the API would return
// after denormalisation (team colour/name baked in, no client-side joins).
// ============================================================================

// Bio: height / age / experience / jersey / position, straight from dim_players.
// Already in the model, previously unused. Coverage is 93-100% except weight
// (53%), which is dropped rather than rendered as a gap. College, draft and
// honours are NOT in wehoop — those need Wikidata (CC0) and land as optional.

// Team bio derived from dim_games home fixtures: primary arena, any alternate
// venues, and mean attendance over games that have reported it. No new source.
// College/founded/coach would come from Wikidata (CC0) and slot in alongside.

// Shot fingerprint, computed from fact_pbp (23,867 FG attempts with zone+result).
// Validated: per-player pbp shot counts reconcile exactly against
// fact_player_box FGA — league total off by 1 in 23,866. LG = league baselines.
// Only players with 60+ FGA; below that a five-way zone split is noise.

// Data is generated by scripts/build_data.py from data/csv/*.csv.
// Never hand-edit src/data/app-data.json — regenerate with `npm run data`.
const RAW = DATA;
const BIO = DATA.BIO || {};
const TEAM_BIO = DATA.TEAM_BIO || {};
const SHOTS = DATA.SHOTS || { LG: null, P: {} };   // null when fact_pbp is absent

const TEAMS = RAW.T.map(([id, abbr, name, shortName, color, conf]) => ({ id, abbr, name, shortName, color, conf, bio: TEAM_BIO[id] || {} }));
const TEAM = Object.fromEntries(TEAMS.map(t => [t.id, t]));
const STANDINGS = RAW.S.map(([id, w, l, pct, pf, pa, diff, streak, l10, home, road]) =>
  ({ id, w, l, pct, pf, pa, diff, streak, l10, home, road, ...TEAM[id] }));
const PLAYERS = RAW.P.map(([id, name, teamId, pos, gp, mpg, ppg, rpg, apg, spg, bpg, topg, fg, tp, ft, ts, usg, tpa]) =>
  ({ id, name, teamId, pos, gp, mpg, ppg, rpg, apg, spg, bpg, topg, fg, tp, ft, ts, usg, tpa, team: TEAM[teamId], bio: BIO[id] || {} }));
const GAMES = RAW.G.map(([id, date, homeId, awayId, hs, as_, net, tier, city, done]) =>
  ({ id, date, homeId, awayId, hs, as: as_, net, tier, city, done: !!done, home: TEAM[homeId], away: TEAM[awayId] }));
const NEWS = RAW.N.map(([headline, byline, abbr, date]) => ({ headline, byline, abbr, date }));

// ---- theme (from wnba-chalk-court-theme.json) --------------------------------
const C = {
  page: "#F4F2EC", card: "#ECEAE2", visual: "#FFFFFF", stripe: "#F7F6F1",
  border: "#DEDBD2", rule: "#15151C", text: "#15151C", sec: "#5B6472",
  mute: "#8A8F98", accent: "#FE5000", good: "#1E8F5E", bad: "#C23934", blue: "#3B6FC4",
};
const DISPLAY = "'Oswald', sans-serif";
const BODY = "'Roboto', system-ui, sans-serif";
const agate = { fontVariantNumeric: "tabular-nums", fontFeatureSettings: "'tnum'" };

// ---- ASSET LAYER ------------------------------------------------------------
// Team crests and player faces are three separate rights (trademark on the mark,
// copyright on the photo, right of publicity on the likeness) and NO data
// provider licenses them for the WNBA today. So imagery is a *slot*: if a
// licensed URL exists we render it, otherwise we render a typographic fallback
// that is ours outright and ships legally as-is.
//
// To switch on real assets later, populate these resolvers with your own CDN
// (never hot-link a third party's) and everything downstream just works.
const ASSETS = {
  crestUrl: (_team) => null,   // e.g. t => `https://cdn.yourdomain/crests/${t.abbr}.svg`
  faceUrl: (_player) => null,  // e.g. p => `https://cdn.yourdomain/faces/${p.id}.webp`
};

// Several club colours are near-white (POR #cee5eb, LV #a7a8aa). Picking text
// colour by luminance rather than assuming white keeps every crest legible.
function readableOn(hex) {
  const h = hex.replace("#", "");
  const [r, g, b] = [0, 2, 4].map(i => parseInt(h.slice(i, i + 2), 16) / 255);
  const lin = (c) => (c <= 0.03928 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4));
  const L = 0.2126 * lin(r) + 0.7152 * lin(g) + 0.0722 * lin(b);
  return L > 0.45 ? C.text : "#FFFFFF";
}

// Letterpress monogram — the club's own colour and letters, set like an agate
// page would. Recognisable at 20px, which a detailed crest never is.
function Crest({ team, size = 30 }) {
  const url = ASSETS.crestUrl(team);
  if (url) return <img src={url} alt="" width={size} height={size} style={{ display: "block", objectFit: "contain", flexShrink: 0 }} />;
  const fg = readableOn(team.color);
  return (
    <div aria-hidden style={{
      width: size, height: size, background: team.color, flexShrink: 0,
      display: "flex", alignItems: "center", justifyContent: "center",
      borderRadius: 2, border: `1px solid rgba(21,21,28,.14)`,
    }}>
      <span style={{
        fontFamily: DISPLAY, fontWeight: 700, color: fg,
        fontSize: size * 0.4, letterSpacing: size * 0.012, lineHeight: 1,
      }}>{team.abbr}</span>
    </div>
  );
}

function Face({ player, size = 44 }) {
  const url = ASSETS.faceUrl(player);
  const t = player.team;
  if (url) return <img src={url} alt="" width={size} height={size} style={{ display: "block", borderRadius: 99, objectFit: "cover", flexShrink: 0, border: `2px solid ${t.color}` }} />;
  const initials = player.name.split(" ").map(w => w[0]).slice(0, 2).join("");
  const fg = readableOn(t.color);
  return (
    <div aria-hidden style={{
      width: size, height: size, borderRadius: 99, background: t.color, flexShrink: 0,
      display: "flex", alignItems: "center", justifyContent: "center", border: `1px solid rgba(21,21,28,.14)`,
    }}>
      <span style={{ fontFamily: DISPLAY, fontWeight: 600, color: fg, fontSize: size * 0.36, letterSpacing: .5 }}>{initials}</span>
    </div>
  );
}


// percentile among positional peers with >= 8 GP — mirrors the report's
// Selected Player Percentile DAX pattern
function percentile(player, key, higherIsBetter = true) {
  const peers = PLAYERS.filter(p => p.pos === player.pos && p.gp >= 8);
  if (!peers.length) return 0;
  const below = peers.filter(p => (higherIsBetter ? p[key] <= player[key] : p[key] >= player[key])).length;
  return Math.round((below / peers.length) * 100);
}

const fmtDate = (iso) => {
  const d = new Date(iso + "T12:00:00");
  return d.toLocaleDateString("en-US", { month: "short", day: "numeric" }).toUpperCase();
};

export default function CourtsideApp() {
  const [tab, setTab] = useState("home");
  const [stack, setStack] = useState(null); // {type:'team'|'player', id}
  const [search, setSearch] = useState(false);

  const open = (type, id) => { setSearch(false); setStack({ type, id }); };
  const back = () => setStack(null);

  return (
    <div style={{ background: "#D8D5CB", minHeight: "100vh", display: "flex", justifyContent: "center", alignItems: "flex-start", padding: "20px 12px", fontFamily: BODY }}>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Oswald:wght@400;500;600;700&family=Roboto:wght@400;500;700&display=swap');
        .noscroll::-webkit-scrollbar{display:none}
        .noscroll{scrollbar-width:none}
        @media (prefers-reduced-motion: reduce){*{transition:none!important}}
      `}</style>

      <div style={{ width: 393, background: "#111", borderRadius: 42, padding: 10, boxShadow: "0 24px 70px rgba(0,0,0,.4)" }}>
        <div style={{ background: C.page, borderRadius: 33, overflow: "hidden", display: "flex", flexDirection: "column", height: 800 }}>

          <StatusBar />

          {search && <SearchOverlay open={open} close={() => setSearch(false)} />}

          {stack ? (
            stack.type === "team"
              ? <TeamDetail team={TEAM[stack.id]} onBack={back} openPlayer={(id) => open("player", id)} />
              : <PlayerDetail player={PLAYERS.find(p => p.id === stack.id)} onBack={back} openTeam={(id) => open("team", id)} />
          ) : (
            <>
              {tab === "home" && <HomeScreen open={open} onSearch={() => setSearch(true)} />}
              {tab === "teams" && <TeamsScreen open={open} onSearch={() => setSearch(true)} />}
              {tab === "players" && <PlayersScreen open={open} />}
              {tab === "schedule" && <ScheduleScreen />}
              {tab === "more" && <MoreScreen />}
            </>
          )}

          <TabBar tab={tab} setTab={(t) => { setStack(null); setTab(t); }} />
        </div>
      </div>
    </div>
  );
}

// ============================================================================
function StatusBar() {
  return (
    <div style={{ display: "flex", justifyContent: "space-between", padding: "9px 24px 3px", fontSize: 12, fontWeight: 500, color: C.text, ...agate }}>
      <span>9:41</span><span style={{ letterSpacing: 1 }}>▮▮▮ 5G ▮</span>
    </div>
  );
}

function Masthead({ title, sub, onSearch }) {
  return (
    <div style={{ padding: "8px 16px 10px", borderBottom: `2px solid ${C.rule}`, display: "flex", alignItems: "flex-end", justifyContent: "space-between" }}>
      <div style={{ display: "flex", alignItems: "center", gap: 7 }}>
        <span style={{ width: 8, height: 8, borderRadius: 99, background: C.accent }} />
        <span style={{ fontFamily: DISPLAY, fontWeight: 700, fontSize: 18, letterSpacing: 1.2, textTransform: "uppercase", color: C.text }}>{title}</span>
      </div>
      <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
        <span style={{ fontSize: 9.5, color: C.sec, letterSpacing: 1, textTransform: "uppercase", fontWeight: 500 }}>{sub}</span>
        {onSearch && <button onClick={onSearch} aria-label="Search" style={{ border: "none", background: "none", padding: 2, cursor: "pointer", display: "flex" }}><Search size={16} color={C.sec} /></button>}
      </div>
    </div>
  );
}

// Global search: players AND teams from any screen. A stats app is a lookup
// tool — making people navigate to a tab before they can type is friction that
// the search-first sports apps all removed years ago.
function SearchOverlay({ open, close }) {
  const [q, setQ] = useState("");
  const hits = useMemo(() => {
    const t = q.trim().toLowerCase();
    if (!t) return { players: [], teams: [] };
    return {
      teams: TEAMS.filter(x => x.name.toLowerCase().includes(t) || x.abbr.toLowerCase() === t).slice(0, 3),
      players: PLAYERS.filter(x => x.name.toLowerCase().includes(t)).slice(0, 12),
    };
  }, [q]);
  const empty = q.trim() && !hits.players.length && !hits.teams.length;
  return (
    <div style={{ position: "absolute", inset: 0, background: C.page, zIndex: 20, display: "flex", flexDirection: "column", borderRadius: 33 }}>
      <div style={{ display: "flex", alignItems: "center", gap: 8, padding: "12px 14px", borderBottom: `2px solid ${C.rule}` }}>
        <Search size={15} color={C.sec} />
        <input autoFocus value={q} onChange={e => setQ(e.target.value)} placeholder="Players and teams"
          style={{ flex: 1, border: "none", outline: "none", background: "none", fontSize: 15, fontFamily: BODY, color: C.text }} />
        <button onClick={close} style={{ border: "none", background: "none", fontSize: 11.5, color: C.sec, cursor: "pointer", fontWeight: 600, letterSpacing: .5, textTransform: "uppercase", fontFamily: BODY }}>Close</button>
      </div>
      <div className="noscroll" style={{ flex: 1, overflowY: "auto", padding: "0 14px 12px" }}>
        {!q.trim() && <div style={{ padding: "26px 0", textAlign: "center", fontSize: 12, color: C.mute, lineHeight: 1.6 }}>Start typing a player or club.<br />Try “Bueckers” or “Lynx”.</div>}
        {empty && <div style={{ padding: "26px 0", textAlign: "center", fontSize: 12.5, color: C.sec }}>Nothing matches “{q}”.<br /><span style={{ fontSize: 11, color: C.mute }}>Players need 5+ games to appear.</span></div>}
        {hits.teams.length > 0 && <SectionHead>Clubs</SectionHead>}
        {hits.teams.map(t => (
          <button key={t.id} onClick={() => open("team", t.id)} style={{ width: "100%", display: "flex", alignItems: "center", gap: 9, padding: "9px 0", border: "none", borderBottom: `1px solid ${C.border}`, background: "none", cursor: "pointer", textAlign: "left" }}>
            <Crest team={t} size={26} />
            <span style={{ flex: 1, fontSize: 13, color: C.text }}>{t.name}</span>
            <ChevronRight size={13} color={C.mute} />
          </button>
        ))}
        {hits.players.length > 0 && <SectionHead>Players</SectionHead>}
        {hits.players.map(p => (
          <button key={p.id} onClick={() => open("player", p.id)} style={{ width: "100%", display: "flex", alignItems: "center", gap: 9, padding: "8px 0", border: "none", borderBottom: `1px solid ${C.border}`, background: "none", cursor: "pointer", textAlign: "left" }}>
            <Face player={p} size={26} />
            <span style={{ flex: 1, fontSize: 12.5, color: C.text }}>{p.name}
              <span style={{ color: C.mute, fontSize: 9.5, marginLeft: 5 }}>{p.team.abbr} · {p.pos}</span></span>
            <span style={{ fontFamily: DISPLAY, fontSize: 13, fontWeight: 600, ...agate, color: C.sec }}>{p.ppg}</span>
          </button>
        ))}
      </div>
    </div>
  );
}

// ---- the score rail: the strip every sports app has, in agate ---------------
function ScoreRail({ open }) {
  const days = useMemo(() => {
    const m = {};
    GAMES.forEach(g => { (m[g.date] ||= []).push(g); });
    return Object.entries(m).slice(0, 6);
  }, []);
  return (
    <div className="noscroll" style={{ display: "flex", gap: 0, overflowX: "auto", background: C.visual, borderBottom: `1px solid ${C.border}` }}>
      {days.map(([date, gs]) => (
        <div key={date} style={{ borderRight: `1px solid ${C.border}`, flexShrink: 0 }}>
          <div style={{ fontSize: 8.5, letterSpacing: 1, color: C.sec, padding: "5px 10px 3px", fontWeight: 700, textTransform: "uppercase", background: C.stripe }}>{fmtDate(date)}</div>
          <div style={{ display: "flex" }}>
            {gs.map(g => (
              <button key={g.id} style={{ border: "none", background: "none", padding: "6px 10px 8px", borderRight: `1px solid ${C.stripe}`, textAlign: "left", cursor: "pointer" }}>
                <RailSide t={g.away} score={g.as} win={g.done && g.as > g.hs} done={g.done} />
                <RailSide t={g.home} score={g.hs} win={g.done && g.hs > g.as} done={g.done} />
                {!g.done && <div style={{ fontSize: 7.5, color: g.tier === "N" ? C.accent : C.mute, fontWeight: 700, marginTop: 2, letterSpacing: .3 }}>{g.net.replace("WNBA ", "")}</div>}
              </button>
            ))}
          </div>
        </div>
      ))}
    </div>
  );
}
function RailSide({ t, score, win, done }) {
  return (
    <div style={{ display: "flex", alignItems: "center", gap: 5, minWidth: 62 }}>
      <span style={{ width: 6, height: 6, borderRadius: 99, background: t.color, flexShrink: 0 }} />
      <span style={{ fontSize: 11, fontWeight: win ? 700 : 400, color: C.text, flex: 1 }}>{t.abbr}</span>
      <span style={{ fontFamily: DISPLAY, fontSize: 12.5, fontWeight: win ? 700 : 400, color: done ? (win ? C.text : C.mute) : C.mute, ...agate }}>{done ? score : "–"}</span>
    </div>
  );
}

// ---- shared agate table primitives -----------------------------------------
function SectionHead({ children, action }) {
  return (
    <div style={{ display: "flex", alignItems: "baseline", justifyContent: "space-between", padding: "14px 0 5px", borderBottom: `1.5px solid ${C.rule}`, marginBottom: 2 }}>
      <span style={{ fontFamily: DISPLAY, fontWeight: 600, fontSize: 13.5, letterSpacing: 1.4, textTransform: "uppercase", color: C.text }}>{children}</span>
      {action && <span style={{ fontSize: 9.5, color: C.sec, letterSpacing: .6, textTransform: "uppercase" }}>{action}</span>}
    </div>
  );
}
const thStyle = { fontSize: 8.5, letterSpacing: .8, textTransform: "uppercase", color: C.sec, fontWeight: 700, padding: "5px 0 4px", borderBottom: `1px solid ${C.border}`, textAlign: "right" };
const tdStyle = { fontSize: 11.5, padding: "6px 0", textAlign: "right", color: C.text, ...agate };

// ============================================================================
function HomeScreen({ open, onSearch }) {
  const [conf, setConf] = useState("All");
  const rows = useMemo(() => {
    let r = conf === "All" ? STANDINGS : STANDINGS.filter(s => s.conf === (conf === "East" ? "East" : "West"));
    const lead = r[0];
    return r.map(s => ({ ...s, gb: s === lead ? 0 : ((lead.w - s.w) + (s.l - lead.l)) / 2 }));
  }, [conf]);
  const leaders = PLAYERS.filter(p => p.gp >= 10).slice(0, 5);

  return (
    <>
      <Masthead title="Courtside" sub="2026 · WK 10" onSearch={onSearch} />
      <ScoreRail open={open} />
      <div className="noscroll" style={{ flex: 1, overflowY: "auto", padding: "0 14px 12px" }}>

        <SectionHead action={`${rows.length} teams`}>Standings</SectionHead>
        <div style={{ display: "flex", gap: 0, margin: "8px 0 2px", border: `1px solid ${C.border}`, borderRadius: 3, overflow: "hidden" }}>
          {["All", "East", "West"].map(v => (
            <button key={v} onClick={() => setConf(v)} style={{
              flex: 1, border: "none", padding: "6px 0", fontSize: 11, fontWeight: 700, letterSpacing: .8, textTransform: "uppercase",
              background: conf === v ? C.rule : C.visual, color: conf === v ? "#fff" : C.sec, cursor: "pointer", fontFamily: BODY,
            }}>{v}</button>
          ))}
        </div>
        <table style={{ width: "100%", borderCollapse: "collapse" }}>
          <thead><tr>
            <th style={{ ...thStyle, textAlign: "left", width: 16 }}></th>
            <th style={{ ...thStyle, textAlign: "left" }}>Team</th>
            <th style={thStyle}>W</th><th style={thStyle}>L</th><th style={thStyle}>PCT</th>
            <th style={thStyle}>GB</th><th style={thStyle}>DIFF</th><th style={thStyle}>STRK</th>
          </tr></thead>
          <tbody>
            {rows.map((s, i) => (
              <tr key={s.id} onClick={() => open("team", s.id)} style={{ background: i % 2 ? C.stripe : "transparent", cursor: "pointer", borderBottom: (conf === "All" && i === 7) ? `2px dashed ${C.accent}` : `1px solid ${C.border}` }}>
                <td style={{ ...tdStyle, textAlign: "left", color: i < 8 ? C.accent : C.mute, fontWeight: 700, fontSize: 10 }}>{i + 1}</td>
                <td style={{ ...tdStyle, textAlign: "left" }}>
                  <span style={{ display: "flex", alignItems: "center", gap: 6 }}>
                    <span style={{ width: 3, height: 13, background: s.color, flexShrink: 0 }} />
                    <b style={{ fontWeight: 500 }}>{s.abbr}</b>
                  </span>
                </td>
                <td style={tdStyle}>{s.w}</td><td style={tdStyle}>{s.l}</td>
                <td style={tdStyle}>{s.pct.toFixed(3).replace(/^0/, "")}</td>
                <td style={{ ...tdStyle, color: C.sec }}>{s.gb === 0 ? "–" : s.gb}</td>
                <td style={{ ...tdStyle, color: s.diff > 0 ? C.good : C.bad }}>{s.diff > 0 ? "+" : ""}{s.diff}</td>
                <td style={{ ...tdStyle, fontWeight: 700, color: s.streak[0] === "W" ? C.good : C.bad }}>{s.streak}</td>
              </tr>
            ))}
          </tbody>
        </table>
        {conf === "All" && <div style={{ fontSize: 8.5, color: C.accent, letterSpacing: .8, textTransform: "uppercase", fontWeight: 700, textAlign: "right", paddingTop: 4 }}>— playoff line, top 8</div>}

        <SectionHead action="PPG · min 10 GP">Leaders</SectionHead>
        {leaders.map((p, i) => (
          <button key={p.id} onClick={() => open("player", p.id)} style={{ width: "100%", border: "none", background: i % 2 ? C.stripe : "transparent", borderBottom: `1px solid ${C.border}`, display: "flex", alignItems: "center", gap: 8, padding: "7px 0", cursor: "pointer", textAlign: "left" }}>
            <span style={{ fontSize: 10, color: C.mute, width: 12, ...agate }}>{i + 1}</span>
            <Face player={p} size={26} />
            <span style={{ flex: 1, fontSize: 12.5, color: C.text }}>{p.name}<span style={{ color: C.mute, fontSize: 10, marginLeft: 5 }}>{p.team.abbr} · {p.pos}</span></span>
            <span style={{ width: 54, height: 5, background: C.border }}>
              <span style={{ display: "block", height: "100%", width: `${(p.ppg / leaders[0].ppg) * 100}%`, background: C.blue }} />
            </span>
            <span style={{ fontFamily: DISPLAY, fontWeight: 600, fontSize: 14, width: 34, textAlign: "right", ...agate }}>{p.ppg}</span>
          </button>
        ))}

        <SectionHead action="ESPN">Wire</SectionHead>
        {NEWS.map((n, i) => (
          <div key={i} style={{ padding: "9px 0", borderBottom: `1px solid ${C.border}` }}>
            <div style={{ fontSize: 12.5, fontWeight: 500, lineHeight: 1.35, color: C.text }}>{n.headline}</div>
            <div style={{ fontSize: 9.5, color: C.sec, marginTop: 3, letterSpacing: .4, textTransform: "uppercase" }}>
              {n.abbr && <b style={{ color: C.accent }}>{n.abbr} · </b>}{n.byline || "Staff"}
            </div>
          </div>
        ))}
        <div style={{ fontSize: 8.5, color: C.mute, textAlign: "center", padding: "8px 0 2px" }}>Headlines provided by ESPN</div>
      </div>
    </>
  );
}

// ============================================================================
function TeamsScreen({ open, onSearch }) {
  const [conf, setConf] = useState("All");
  const rows = conf === "All" ? STANDINGS : STANDINGS.filter(s => s.conf === conf);
  return (
    <>
      <Masthead title="Teams" sub="15 clubs" onSearch={onSearch} />
      <div className="noscroll" style={{ flex: 1, overflowY: "auto", padding: "0 14px 12px" }}>
        <div style={{ display: "flex", margin: "12px 0 4px", border: `1px solid ${C.border}`, borderRadius: 3, overflow: "hidden" }}>
          {["All", "East", "West"].map(v => (
            <button key={v} onClick={() => setConf(v)} style={{ flex: 1, border: "none", padding: "6px 0", fontSize: 11, fontWeight: 700, letterSpacing: .8, textTransform: "uppercase", background: conf === v ? C.rule : C.visual, color: conf === v ? "#fff" : C.sec, cursor: "pointer", fontFamily: BODY }}>{v}</button>
          ))}
        </div>
        {rows.map((s, i) => (
          <button key={s.id} onClick={() => open("team", s.id)} style={{ width: "100%", display: "flex", alignItems: "center", gap: 10, padding: "11px 0", border: "none", borderBottom: `1px solid ${C.border}`, background: "none", cursor: "pointer", textAlign: "left" }}>
            <Crest team={s} size={34} />
            <span style={{ flex: 1 }}>
              <div style={{ fontFamily: DISPLAY, fontSize: 14.5, fontWeight: 500, letterSpacing: .5, textTransform: "uppercase", color: C.text }}>{s.name}</div>
              <div style={{ fontSize: 9.5, color: C.sec, letterSpacing: .5, textTransform: "uppercase" }}>{s.conf} · {s.pf} PF / {s.pa} PA</div>
            </span>
            <span style={{ textAlign: "right" }}>
              <div style={{ fontFamily: DISPLAY, fontSize: 15, fontWeight: 600, ...agate }}>{s.w}–{s.l}</div>
              <div style={{ fontSize: 10, fontWeight: 700, color: s.streak[0] === "W" ? C.good : C.bad, ...agate }}>{s.streak}</div>
            </span>
          </button>
        ))}
      </div>
    </>
  );
}

// ============================================================================
function PlayersScreen({ open }) {
  const [q, setQ] = useState("");
  const [pos, setPos] = useState("All");
  const [sort, setSort] = useState("ppg");
  const rows = useMemo(() => {
    let r = PLAYERS.filter(p => p.gp >= 8);
    if (pos !== "All") r = r.filter(p => p.pos === pos);
    if (q.trim()) r = r.filter(p => p.name.toLowerCase().includes(q.toLowerCase()));
    return [...r].sort((a, b) => b[sort] - a[sort]).slice(0, 40);
  }, [q, pos, sort]);

  const cols = [["ppg", "PPG"], ["rpg", "REB"], ["apg", "AST"], ["ts", "TS%"], ["usg", "USG"]];

  return (
    <>
      <Masthead title="Players" sub="min 8 GP" />
      <div style={{ padding: "10px 14px 6px", borderBottom: `1px solid ${C.border}` }}>
        <div style={{ display: "flex", alignItems: "center", gap: 7, background: C.visual, border: `1px solid ${C.border}`, borderRadius: 3, padding: "7px 10px" }}>
          <Search size={13} color={C.mute} />
          <input value={q} onChange={e => setQ(e.target.value)} placeholder="Search players" style={{ border: "none", outline: "none", background: "none", flex: 1, fontSize: 12.5, fontFamily: BODY, color: C.text }} />
        </div>
        <div style={{ display: "flex", gap: 5, marginTop: 7 }}>
          {["All", "G", "F", "C"].map(v => (
            <button key={v} onClick={() => setPos(v)} style={{ flex: 1, border: `1px solid ${pos === v ? C.rule : C.border}`, background: pos === v ? C.rule : "transparent", color: pos === v ? "#fff" : C.sec, borderRadius: 3, padding: "4px 0", fontSize: 10.5, fontWeight: 700, letterSpacing: .6, cursor: "pointer", fontFamily: BODY }}>{v}</button>
          ))}
        </div>
      </div>
      <div className="noscroll" style={{ flex: 1, overflowY: "auto", padding: "0 14px 12px" }}>
        <table style={{ width: "100%", borderCollapse: "collapse" }}>
          <thead><tr>
            <th style={{ ...thStyle, textAlign: "left", position: "sticky", top: 0, background: C.page }}>Player</th>
            {cols.map(([k, l]) => (
              <th key={k} onClick={() => setSort(k)} style={{ ...thStyle, position: "sticky", top: 0, background: C.page, cursor: "pointer", color: sort === k ? C.accent : C.sec }}>{l}</th>
            ))}
          </tr></thead>
          <tbody>
            {rows.map((p, i) => (
              <tr key={p.id + "-" + i} onClick={() => open("player", p.id)} style={{ background: i % 2 ? C.stripe : "transparent", borderBottom: `1px solid ${C.border}`, cursor: "pointer" }}>
                <td style={{ ...tdStyle, textAlign: "left" }}>
                  <span style={{ display: "flex", alignItems: "center", gap: 6 }}>
                    <span style={{ width: 3, height: 14, background: p.team.color, flexShrink: 0 }} />
                    <span>
                      <span style={{ fontSize: 11.5 }}>{p.name}</span>
                      <span style={{ fontSize: 9, color: C.mute, marginLeft: 4 }}>{p.team.abbr}·{p.pos}</span>
                    </span>
                  </span>
                </td>
                {cols.map(([k]) => <td key={k} style={{ ...tdStyle, fontWeight: sort === k ? 700 : 400 }}>{p[k]}</td>)}
              </tr>
            ))}
          </tbody>
        </table>
        {!rows.length && <div style={{ padding: 30, textAlign: "center", color: C.sec, fontSize: 12.5 }}>No players match “{q}”. Try a shorter search.</div>}
      </div>
    </>
  );
}

// ============================================================================
function ScheduleScreen() {
  const days = useMemo(() => {
    const m = {};
    // Upcoming only: a game is "played" iff it has box-score rows (g.done). Show the rest.
    GAMES.filter(g => !g.done)
      .slice()
      .sort((a, b) => a.date < b.date ? -1 : a.date > b.date ? 1 : 0)
      .forEach(g => { (m[g.date] ||= []).push(g); });
    return Object.entries(m);
  }, []);
  const upcoming = RAW.meta.totalGames - RAW.meta.completedGames;
  return (
    <>
      <Masthead title="Schedule" sub={`${upcoming} upcoming`} />
      <div className="noscroll" style={{ flex: 1, overflowY: "auto", padding: "0 14px 12px" }}>
        {days.length === 0 && (
          <div style={{ textAlign: "center", color: C.mute, fontSize: 12, padding: "40px 0" }}>
            No upcoming games — the season is complete.
          </div>
        )}
        {days.map(([date, gs]) => (
          <div key={date}>
            <div style={{ fontSize: 9.5, fontWeight: 700, letterSpacing: 1.2, textTransform: "uppercase", color: C.sec, padding: "12px 0 4px", borderBottom: `1.5px solid ${C.rule}` }}>
              {new Date(date + "T12:00:00").toLocaleDateString("en-US", { weekday: "long", month: "short", day: "numeric" })}
            </div>
            {gs.map(g => (
              <div key={g.id} style={{ display: "flex", alignItems: "center", gap: 8, padding: "9px 0", borderBottom: `1px solid ${C.border}` }}>
                <div style={{ flex: 1 }}>
                  <SchedSide t={g.away} score={g.as} win={g.done && g.as > g.hs} done={g.done} />
                  <SchedSide t={g.home} score={g.hs} win={g.done && g.hs > g.as} done={g.done} prefix="vs" />
                </div>
                <div style={{ textAlign: "right", minWidth: 74 }}>
                  <div style={{ fontSize: 9, fontWeight: 700, letterSpacing: .5, textTransform: "uppercase", color: g.tier === "N" ? C.accent : C.mute, border: g.tier === "N" ? `1px solid ${C.accent}` : "none", borderRadius: 2, padding: g.tier === "N" ? "2px 5px" : 0, display: "inline-block" }}>{g.net.replace("WNBA ", "")}</div>
                  <div style={{ fontSize: 9, color: C.mute, marginTop: 3 }}>{g.city}</div>
                </div>
              </div>
            ))}
          </div>
        ))}
      </div>
    </>
  );
}
function SchedSide({ t, score, win, done, prefix }) {
  return (
    <div style={{ display: "flex", alignItems: "center", gap: 7, padding: "1px 0" }}>
      <span style={{ width: 3, height: 12, background: t.color, flexShrink: 0 }} />
      <span style={{ fontSize: 12, fontWeight: win ? 700 : 400, color: C.text, flex: 1 }}>{prefix && <span style={{ color: C.mute, fontSize: 9.5 }}>{prefix} </span>}{t.name}</span>
      <span style={{ fontFamily: DISPLAY, fontSize: 14, fontWeight: win ? 700 : 400, color: done ? (win ? C.text : C.mute) : C.mute, ...agate }}>{done ? score : "–"}</span>
    </div>
  );
}

// ============================================================================
function DetailHead({ color, onBack, eyebrow, title, right, badge }) {
  return (
    <div style={{ borderBottom: `2px solid ${C.rule}`, background: C.visual }}>
      <div style={{ height: 4, background: color }} />
      <div style={{ display: "flex", alignItems: "center", gap: 4, padding: "8px 12px 10px" }}>
        <button onClick={onBack} style={{ border: "none", background: "none", padding: 4, cursor: "pointer", display: "flex" }}><ChevronLeft size={19} color={C.text} /></button>
        {badge}
        <div style={{ flex: 1 }}>
          <div style={{ fontSize: 8.5, letterSpacing: 1.1, textTransform: "uppercase", color: C.sec, fontWeight: 700 }}>{eyebrow}</div>
          <div style={{ fontFamily: DISPLAY, fontSize: 19, fontWeight: 600, letterSpacing: .6, textTransform: "uppercase", color: C.text, lineHeight: 1.1 }}>{title}</div>
        </div>
        {right}
      </div>
    </div>
  );
}

function SubTabs({ tabs, active, set }) {
  return (
    <div style={{ display: "flex", borderBottom: `1px solid ${C.border}`, background: C.visual }}>
      {tabs.map(t => (
        <button key={t} onClick={() => set(t)} style={{
          flex: 1, border: "none", background: "none", padding: "9px 0", cursor: "pointer",
          fontSize: 10.5, fontWeight: 700, letterSpacing: .9, textTransform: "uppercase",
          color: active === t ? C.text : C.mute, borderBottom: active === t ? `2.5px solid ${C.accent}` : "2.5px solid transparent", fontFamily: BODY,
        }}>{t}</button>
      ))}
    </div>
  );
}

function TeamDetail({ team, onBack, openPlayer }) {
  const [sub, setSub] = useState("Overview");
  const s = STANDINGS.find(x => x.id === team.id);
  const roster = PLAYERS.filter(p => p.teamId === team.id).sort((a, b) => b.ppg - a.ppg);
  const games = GAMES.filter(g => g.homeId === team.id || g.awayId === team.id);
  const rank = STANDINGS.findIndex(x => x.id === team.id) + 1;

  return (
    <>
      <DetailHead color={team.color} onBack={onBack} badge={<Crest team={team} size={34} />} eyebrow={`${s.conf} · #${rank} league`} title={team.name}
        right={<div style={{ textAlign: "right" }}>
          <div style={{ fontFamily: DISPLAY, fontSize: 21, fontWeight: 700, ...agate }}>{s.w}–{s.l}</div>
          <div style={{ fontSize: 10, fontWeight: 700, color: s.streak[0] === "W" ? C.good : C.bad, ...agate }}>{s.streak}</div>
        </div>} />
      <SubTabs tabs={["Overview", "Roster", "Games"]} active={sub} set={setSub} />
      <div className="noscroll" style={{ flex: 1, overflowY: "auto", padding: "0 14px 12px" }}>
        {sub === "Overview" && <>
          <TeamBio team={team} />
          <SectionHead>Season</SectionHead>
          <StatGrid items={[
            ["Win %", s.pct.toFixed(3).replace(/^0/, "")], ["Pts For", s.pf], ["Pts Against", s.pa],
            ["Point Diff", (s.diff > 0 ? "+" : "") + s.diff], ["Home", s.home], ["Road", s.road],
            ["Last 10", s.l10], ["Streak", s.streak],
          ]} />
          <SectionHead action="league avg 86.3">Scoring</SectionHead>
          <Bar label="Points for" v={s.pf} max={95} color={C.blue} />
          <Bar label="Points against" v={s.pa} max={95} color={C.sec} />
          <SectionHead>Top scorers</SectionHead>
          {roster.slice(0, 5).map((p, i) => (
            <button key={p.id} onClick={() => openPlayer(p.id)} style={{ width: "100%", display: "flex", alignItems: "center", gap: 8, padding: "7px 0", border: "none", borderBottom: `1px solid ${C.border}`, background: i % 2 ? C.stripe : "none", cursor: "pointer", textAlign: "left" }}>
              <span style={{ fontSize: 10, color: C.mute, width: 12, ...agate }}>{i + 1}</span>
              <span style={{ flex: 1, fontSize: 12.5 }}>{p.name}<span style={{ color: C.mute, fontSize: 9.5, marginLeft: 4 }}>{p.pos}</span></span>
              <span style={{ fontFamily: DISPLAY, fontSize: 14, fontWeight: 600, ...agate }}>{p.ppg}</span>
            </button>
          ))}
        </>}
        {sub === "Roster" && <>
          <table style={{ width: "100%", borderCollapse: "collapse", marginTop: 6 }}>
            <thead><tr>
              <th style={{ ...thStyle, textAlign: "left" }}>Player</th>
              {["GP", "MPG", "PPG", "REB", "AST", "TS%"].map(h => <th key={h} style={thStyle}>{h}</th>)}
            </tr></thead>
            <tbody>
              {roster.map((p, i) => (
                <tr key={p.id} onClick={() => openPlayer(p.id)} style={{ background: i % 2 ? C.stripe : "transparent", borderBottom: `1px solid ${C.border}`, cursor: "pointer" }}>
                  <td style={{ ...tdStyle, textAlign: "left", fontSize: 11 }}>{p.name}<span style={{ color: C.mute, fontSize: 9, marginLeft: 3 }}>{p.pos}</span></td>
                  <td style={tdStyle}>{p.gp}</td><td style={tdStyle}>{p.mpg}</td>
                  <td style={{ ...tdStyle, fontWeight: 700 }}>{p.ppg}</td>
                  <td style={tdStyle}>{p.rpg}</td><td style={tdStyle}>{p.apg}</td><td style={tdStyle}>{p.ts}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </>}
        {sub === "Games" && <TeamSeason team={team} />}
      </div>
    </>
  );
}

function StatGrid({ items }) {
  return (
    <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 0, borderTop: `1px solid ${C.border}` }}>
      {items.map(([k, v], i) => (
        <div key={k} style={{ padding: "8px 10px", borderBottom: `1px solid ${C.border}`, borderRight: i % 2 === 0 ? `1px solid ${C.border}` : "none", background: Math.floor(i / 2) % 2 ? C.stripe : "transparent" }}>
          <div style={{ fontSize: 8.5, letterSpacing: .8, textTransform: "uppercase", color: C.sec, fontWeight: 700 }}>{k}</div>
          <div style={{ fontFamily: DISPLAY, fontSize: 17, fontWeight: 600, color: C.text, ...agate }}>{v}</div>
        </div>
      ))}
    </div>
  );
}

function Bar({ label, v, max, color }) {
  return (
    <div style={{ padding: "7px 0", borderBottom: `1px solid ${C.border}` }}>
      <div style={{ display: "flex", justifyContent: "space-between", fontSize: 11, color: C.sec, marginBottom: 3 }}>
        <span>{label}</span><b style={{ color: C.text, ...agate }}>{v}</b>
      </div>
      <div style={{ height: 6, background: C.border }}>
        <div style={{ height: "100%", width: `${(v / max) * 100}%`, background: color }} />
      </div>
    </div>
  );
}

function PlayerDetail({ player: p, onBack, openTeam }) {
  const [sub, setSub] = useState("Profile");
  const pcts = [
    ["Points", "ppg", p.ppg, true], ["Rebounds", "rpg", p.rpg, true], ["Assists", "apg", p.apg, true],
    ["True shooting", "ts", p.ts + "%", true], ["Usage", "usg", p.usg + "%", true],
    ["3PT rate", "tpa", p.tpa, true], ["Turnovers", "topg", p.topg, false],
  ];
  return (
    <>
      <DetailHead color={p.team.color} onBack={onBack} badge={<Face player={p} size={38} />} eyebrow={`${p.team.name} · ${p.pos} · ${p.gp} GP`} title={p.name}
        right={<div style={{ textAlign: "right" }}>
          <div style={{ fontFamily: DISPLAY, fontSize: 21, fontWeight: 700, ...agate }}>{p.ppg}</div>
          <div style={{ fontSize: 8.5, color: C.sec, letterSpacing: .8, fontWeight: 700 }}>PPG</div>
        </div>} />
      <SubTabs tabs={["Profile", "Percentiles", "Fingerprint"]} active={sub} set={setSub} />
      <div className="noscroll" style={{ flex: 1, overflowY: "auto", padding: "0 14px 12px" }}>
        {sub === "Profile" && <>
          <BioStrip p={p} />
          <SectionHead action="per game">Season</SectionHead>
          <StatGrid items={[
            ["Minutes", p.mpg], ["Points", p.ppg], ["Rebounds", p.rpg], ["Assists", p.apg],
            ["Steals", p.spg], ["Blocks", p.bpg], ["Turnovers", p.topg], ["Usage", p.usg + "%"],
          ]} />
          <SectionHead>Club</SectionHead>
          <button onClick={() => openTeam(p.teamId)} style={{ width: "100%", display: "flex", alignItems: "center", gap: 10, padding: "12px 0", border: "none", borderBottom: `1px solid ${C.border}`, background: "none", cursor: "pointer", textAlign: "left" }}>
            <Crest team={p.team} size={30} />
            <span style={{ flex: 1, fontFamily: DISPLAY, fontSize: 14.5, letterSpacing: .5, textTransform: "uppercase" }}>{p.team.name}</span>
            <ChevronLeft size={15} color={C.mute} style={{ transform: "rotate(180deg)" }} />
          </button>
        </>}
        {sub === "Percentiles" && <>
          <SectionHead action={`vs ${p.pos} · min 8 GP`}>Peer rank</SectionHead>
          {pcts.map(([label, key, val, hib]) => {
            const pc = percentile(p, key, hib);
            return (
              <div key={key} style={{ padding: "9px 0", borderBottom: `1px solid ${C.border}` }}>
                <div style={{ display: "flex", justifyContent: "space-between", alignItems: "baseline", marginBottom: 4 }}>
                  <span style={{ fontSize: 11.5, color: C.sec }}>{label}</span>
                  <span style={{ fontSize: 11.5, ...agate }}>
                    <b style={{ color: C.text }}>{val}</b>
                    <span style={{ color: pc >= 75 ? C.good : pc <= 25 ? C.bad : C.mute, marginLeft: 7, fontWeight: 700 }}>{pc}th</span>
                  </span>
                </div>
                <div style={{ height: 7, background: C.border, position: "relative" }}>
                  <div style={{ height: "100%", width: `${pc}%`, background: pc >= 75 ? C.blue : pc <= 25 ? C.bad : C.sec }} />
                  <div style={{ position: "absolute", left: "50%", top: -2, bottom: -2, width: 1, background: C.rule, opacity: .35 }} />
                </div>
              </div>
            );
          })}
          <div style={{ fontSize: 9, color: C.mute, paddingTop: 8, lineHeight: 1.5 }}>
            Percentile vs. same-position players with 8+ games. Centre rule marks the positional median. Turnovers inverted — lower is better.
          </div>
        </>}
        {sub === "Fingerprint" && <ShotFingerprint p={p} />}
      </div>
    </>
  );
}

// ============================================================================
// More / Support. No ads — so this is where the tip jar lives, alongside the
// attribution and data-source disclosure the store listing needs anyway.
// Deliberately the last tab: it should be findable, never in the way.
function MoreScreen() {
  return (
    <>
      <Masthead title="About" sub="sources · credits" />
      <div className="noscroll" style={{ flex: 1, overflowY: "auto", padding: "0 14px 16px" }}>

        <SectionHead>Where the numbers come from</SectionHead>
        <Row icon={Database} label="Data source" value="TBD — licensed feed" />
        <Row icon={FileText} label="Last updated" value="12 Jul 2026, 23:40" />
        <Row icon={Github} label="Source code" value="Open" />
        <Row icon={Coffee} label="Version" value="0.3.0" />

        <SectionHead>How to read this</SectionHead>
        <p style={{ fontSize: 11.5, lineHeight: 1.6, color: C.sec, padding: "8px 0 0", margin: 0 }}>
          Percentiles compare a player against others at the same position with eight or more games.
          Usage rate is an estimate and isn't adjusted for team pace. A game counts as final once its
          box score lands, which can trail the schedule by a few hours.
        </p>

        <SectionHead>Credits</SectionHead>
        <p style={{ fontSize: 11.5, lineHeight: 1.6, color: C.sec, padding: "8px 0 0", margin: 0 }}>
          Courtside is a free, independent project. No ads, no tracking, no accounts.
          It isn't affiliated with, endorsed by, or connected to the WNBA or any of its clubs.
          Club names and abbreviations identify whose results are shown, nothing more.
        </p>
      </div>
    </>
  );
}

function Row({ icon: Icon, label, value }) {
  return (
    <button style={{ width: "100%", display: "flex", alignItems: "center", gap: 9, padding: "11px 0", border: "none", borderBottom: `1px solid ${C.border}`, background: "none", cursor: "pointer", textAlign: "left", fontFamily: BODY }}>
      <Icon size={14} color={C.sec} strokeWidth={1.8} />
      <span style={{ flex: 1, fontSize: 12, color: C.text }}>{label}</span>
      <span style={{ fontSize: 11, color: C.mute, ...agate }}>{value}</span>
      <ChevronRight size={13} color={C.mute} />
    </button>
  );
}


// Bio facts from dim_players. Every field is optional — Wikidata-sourced
// college/honours will be patchy for rookies and international players, so the
// strip has to degrade rather than leave holes.
function BioStrip({ p }) {
  const b = p.bio || {};
  const facts = [
    b.no && ["No.", b.no],
    b.posFull && ["Position", b.posFull],
    b.h && ["Height", b.h],
    b.age && ["Age", b.age],
    b.exp != null && ["Experience", b.exp === 0 ? "Rookie" : `${b.exp} yr${b.exp > 1 ? "s" : ""}`],
    b.college && ["College", b.college],   // Wikidata (CC0) — see scripts/wikidata_bio.py
  ].filter(Boolean);
  if (!facts.length) return null;
  return (
    <div className="noscroll" style={{ display: "flex", gap: 0, overflowX: "auto", borderBottom: `1px solid ${C.border}`, marginTop: 2 }}>
      {facts.map(([k, v], i) => (
        <div key={k} style={{ padding: "9px 13px 9px 0", marginRight: 13, borderRight: i < facts.length - 1 ? `1px solid ${C.border}` : "none", flexShrink: 0 }}>
          <div style={{ fontSize: 8, letterSpacing: .9, textTransform: "uppercase", color: C.sec, fontWeight: 700 }}>{k}</div>
          <div style={{ fontFamily: DISPLAY, fontSize: 15, fontWeight: 600, color: C.text, ...agate, marginTop: 1 }}>{v}</div>
        </div>
      ))}
    </div>
  );
}


// Home venue(s) and attendance, both derived from dim_games. The alternate-venue
// line matters more than it looks: Toronto play a touring slate across four
// arenas in three cities, which a single "home arena" field would silently hide.
function TeamBio({ team }) {
  const b = team.bio || {};
  if (!b.arena) return null;
  return (
    <>
      <SectionHead action="derived from fixtures">Home</SectionHead>
      <div style={{ padding: "9px 0", borderBottom: `1px solid ${C.border}` }}>
        <div style={{ fontFamily: DISPLAY, fontSize: 15, fontWeight: 600, color: C.text, letterSpacing: .3 }}>{b.arena}</div>
        <div style={{ fontSize: 11, color: C.sec, marginTop: 1 }}>{b.city} · {b.home} home games</div>
      </div>
      {b.alt?.length > 0 && (
        <div style={{ padding: "8px 0", borderBottom: `1px solid ${C.border}` }}>
          <div style={{ fontSize: 8.5, letterSpacing: .9, textTransform: "uppercase", color: C.sec, fontWeight: 700, marginBottom: 4 }}>Also hosts at</div>
          {b.alt.map(v => (
            <div key={v.n} style={{ display: "flex", justifyContent: "space-between", fontSize: 11.5, padding: "2px 0", color: C.text }}>
              <span>{v.n} <span style={{ color: C.mute }}>· {v.c}</span></span>
              <span style={{ color: C.sec, ...agate }}>{v.g}</span>
            </div>
          ))}
        </div>
      )}
      {b.att && (
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "baseline", padding: "9px 0", borderBottom: `1px solid ${C.border}` }}>
          <span style={{ fontSize: 11.5, color: C.sec }}>Average attendance</span>
          <span><b style={{ fontFamily: DISPLAY, fontSize: 17, ...agate }}>{b.att.toLocaleString()}</b>
            <span style={{ fontSize: 9.5, color: C.mute, marginLeft: 5 }}>{b.attN} games</span></span>
        </div>
      )}
    </>
  );
}

// A team's season is two different questions wearing one coat: "how have they
// been going?" (newest first) and "what's next?" (soonest first). One
// chronological list answers neither well — you land in May and scroll past two
// months of history to find tonight. Split the sort, keep the data.
function TeamSeason({ team }) {
  const all = useMemo(() => {
    const gs = GAMES.filter(g => g.homeId === team.id || g.awayId === team.id)
      .sort((a, b) => a.date.localeCompare(b.date));
    let w = 0, l = 0;
    return gs.map(g => {
      const isHome = g.homeId === team.id;
      const us = isHome ? g.hs : g.as, them = isHome ? g.as : g.hs;
      const won = g.done && us > them;
      if (g.done) (won ? w++ : l++);
      return { g, isHome, us, them, won, opp: isHome ? g.away : g.home,
               rec: g.done ? `${w}-${l}` : null, margin: g.done ? us - them : null };
    });
  }, [team.id]);

  const results  = useMemo(() => all.filter(r => r.g.done).slice().reverse(), [all]); // newest first
  const fixtures = useMemo(() => all.filter(r => !r.g.done), [all]);                   // soonest first
  const [view, setView] = useState(results.length ? "Results" : "Fixtures");
  const rows = view === "Results" ? results : fixtures;

  // Form: last 10, oldest->newest left to right, the way every league table prints it.
  const form = all.filter(r => r.g.done).slice(-10);

  const months = useMemo(() => {
    const m = [];
    rows.forEach(r => {
      const k = new Date(r.g.date + "T12:00:00").toLocaleDateString("en-US", { month: "long" });
      if (!m.length || m[m.length - 1][0] !== k) m.push([k, []]);
      m[m.length - 1][1].push(r);
    });
    return m;
  }, [rows]);

  return (
    <>
      <div style={{ display: "flex", gap: 0, margin: "10px 0 2px", border: `1px solid ${C.border}`, borderRadius: 3, overflow: "hidden" }}>
        {[["Results", results.length], ["Fixtures", fixtures.length]].map(([v, n]) => (
          <button key={v} onClick={() => setView(v)} style={{
            flex: 1, border: "none", padding: "7px 0", fontSize: 11, fontWeight: 700, letterSpacing: .8,
            textTransform: "uppercase", cursor: "pointer", fontFamily: BODY,
            background: view === v ? C.rule : C.visual, color: view === v ? "#fff" : C.sec,
          }}>{v} <span style={{ opacity: .6, fontWeight: 500 }}>{n}</span></button>
        ))}
      </div>

      {view === "Results" && form.length > 0 && (
        <div style={{ display: "flex", alignItems: "center", gap: 8, padding: "9px 0", borderBottom: `1px solid ${C.border}` }}>
          <span style={{ fontSize: 8.5, letterSpacing: .9, textTransform: "uppercase", color: C.sec, fontWeight: 700 }}>Last {form.length}</span>
          <div style={{ display: "flex", gap: 3, flex: 1 }}>
            {form.map(r => (
              <span key={r.g.id} title={`${r.won ? "W" : "L"} ${r.us}-${r.them}`} style={{
                flex: 1, height: 15, background: r.won ? C.good : C.bad, opacity: .18 + Math.min(Math.abs(r.margin), 20) / 20 * .82,
                borderRadius: 1,
              }} />
            ))}
          </div>
          <span style={{ fontSize: 9, color: C.mute }}>opacity = margin</span>
        </div>
      )}

      {months.map(([month, gs]) => (
        <div key={month + gs[0].g.id}>
          <div style={{ fontSize: 9.5, fontWeight: 700, letterSpacing: 1.2, textTransform: "uppercase", color: C.sec, padding: "11px 0 4px", borderBottom: `1.5px solid ${C.rule}` }}>{month}</div>
          {gs.map(({ g, isHome, us, them, won, opp, rec, margin }) => (
            <div key={g.id} style={{ display: "flex", alignItems: "center", gap: 7, padding: "8px 0", borderBottom: `1px solid ${C.border}` }}>
              <span style={{ fontSize: 10, color: C.mute, width: 20, textAlign: "right", ...agate }}>
                {new Date(g.date + "T12:00:00").getDate()}
              </span>
              <span style={{ fontSize: 9.5, color: C.mute, width: 13 }}>{isHome ? "vs" : "@"}</span>
              <Crest team={opp} size={19} />
              <span style={{ flex: 1, fontSize: 11.5, color: C.text }}>{opp.abbr}</span>
              {g.done ? (
                <>
                  <span style={{ fontSize: 10, fontWeight: 700, color: won ? C.good : C.bad, width: 11 }}>{won ? "W" : "L"}</span>
                  <span style={{ fontFamily: DISPLAY, fontSize: 13, fontWeight: 600, width: 46, textAlign: "right", ...agate }}>{us}–{them}</span>
                  <span style={{ fontSize: 9, color: C.mute, width: 28, textAlign: "right", ...agate }}>{rec}</span>
                </>
              ) : (
                <>
                  <span style={{ fontSize: 9.5, color: C.mute, width: 46, textAlign: "right", ...agate }}>
                    {new Date(g.date + "T12:00:00").toLocaleDateString("en-US", { weekday: "short" })}
                  </span>
                  <span style={{ fontSize: 8.5, color: g.tier === "N" ? C.accent : C.mute, fontWeight: 700, textTransform: "uppercase", width: 62, textAlign: "right" }}>
                    {g.net.replace("WNBA ", "")}
                  </span>
                </>
              )}
            </div>
          ))}
        </div>
      ))}
      {!rows.length && <div style={{ padding: 30, textAlign: "center", fontSize: 12, color: C.sec }}>
        {view === "Results" ? "No games played yet." : "Season complete — no fixtures left."}
      </div>}
    </>
  );
}


// ---- SHOT FINGERPRINT -------------------------------------------------------
// Zones are spatial, so they're drawn on a court, not a radar. A radar's spoke
// order is arbitrary — reorder the axes and the same player gets a different
// silhouette, which is fatal for something whose whole claim is "this shape is
// this player". The floor is the honest projection of floor data.
//
// Labels live ON the court. The hard part is that zone areas differ ~10x: the
// corner is a 3ft sliver and above-the-break is the whole width. Solved by
// rotating the corner label 90deg so its length runs down the corner's 7.8ft
// height rather than across its 3ft width. Every label position below was
// checked against the zone's actual free space, not eyeballed.
const CW = 50, CD = 35, HOOP_Y = 5.25, ARC_R = 22.15, RA_R = 4, CORNER_X = 3;
const sy = (courtY) => CD - courtY;
const CORNER_MEET = HOOP_Y + Math.sqrt(ARC_R ** 2 - (CW / 2 - CORNER_X) ** 2); // 7.82
const ARC_APEX = HOOP_Y + ARC_R;                                               // 27.40

function arcPath() {
  // Snap the ends to exactly where the corner lines meet the arc — sampling
  // alone leaves a visible ~1ft gap at each corner.
  const pts = [[CORNER_X, sy(CORNER_MEET)]];
  for (let i = 0; i <= 90; i++) {
    const a = Math.PI * (i / 90);
    const x = CW / 2 - ARC_R * Math.cos(a);
    const y = HOOP_Y + ARC_R * Math.sin(a);
    if (y >= CORNER_MEET) pts.push([x, sy(y)]);
  }
  pts.push([CW - CORNER_X, sy(CORNER_MEET)]);
  return pts;
}
const ARC_D = "M " + arcPath().map(([x, y]) => `${x.toFixed(2)} ${y.toFixed(2)}`).join(" L ");

// White halo behind glyphs via paint-order, so a label stays legible whether
// its zone is near-white or fully saturated.
const HALO = { stroke: "#FFFFFF", strokeWidth: 0.85, paintOrder: "stroke", strokeLinejoin: "round" };

function ZoneLabel({ x, y, name, value, delta, mode }) {
  if (value == null) return null;
  const dc = delta == null ? C.mute : delta > 0 ? C.good : C.bad;
  return (
    <g transform={`translate(${x} ${y})`}>
      <text textAnchor="middle" y={0} {...HALO}
        style={{ fontSize: 1.45, fontWeight: 700, letterSpacing: 0.12, fill: C.sec }}>
        {name}
      </text>
      <text textAnchor="middle" y={2.9} {...HALO}
        style={{ fontFamily: DISPLAY, fontSize: 2.9, fontWeight: 700, fill: C.text }}>
        {value.toFixed(1)}%
      </text>
      {mode === "eff" && delta != null && (
        <text textAnchor="middle" y={5} {...HALO}
          style={{ fontSize: 1.5, fontWeight: 700, fill: dc }}>
          {delta > 0 ? "+" : ""}{delta.toFixed(1)} vs lg
        </text>
      )}
    </g>
  );
}

function ShotFingerprint({ p }) {
  const [mode, setMode] = useState("freq");
  const d = SHOTS.P[String(p.id)] || SHOTS.P[p.id];

  if (!d) return (
    <div style={{ padding: "34px 10px", textAlign: "center" }}>
      <div style={{ fontFamily: DISPLAY, fontSize: 14, letterSpacing: 1, textTransform: "uppercase", color: C.sec }}>Not enough shots</div>
      <div style={{ fontSize: 11.5, color: C.mute, marginTop: 6, lineHeight: 1.6 }}>
        A fingerprint needs 60+ field goal attempts.<br />Below that, a five-way split is noise, not a profile.
      </div>
    </div>
  );

  const maxF = Math.max(...d.f);
  const tone = (i) => {
    if (mode === "freq") return { c: C.accent, o: 0.07 + (d.f[i] / maxF) * 0.6 };
    if (d.p[i] == null) return { c: C.mute, o: 0.08 };
    const delta = d.p[i] - SHOTS.LG.fg[i];
    return { c: delta >= 0 ? C.good : C.bad, o: 0.09 + Math.min(Math.abs(delta) / 15, 1) * 0.58 };
  };
  const val = (i) => (mode === "freq" ? d.f[i] : d.p[i]);
  const dlt = (i) => (d.p[i] == null ? null : d.p[i] - SHOTS.LG.fg[i]);

  return (
    <>
      <div style={{ display: "flex", margin: "10px 0 8px", border: `1px solid ${C.border}`, borderRadius: 3, overflow: "hidden" }}>
        {[["freq", "Shot diet"], ["eff", "Accuracy vs league"]].map(([k, l]) => (
          <button key={k} onClick={() => setMode(k)} style={{
            flex: 1, border: "none", padding: "7px 0", fontSize: 11, fontWeight: 700, letterSpacing: .7,
            textTransform: "uppercase", cursor: "pointer", fontFamily: BODY,
            background: mode === k ? C.rule : C.visual, color: mode === k ? "#fff" : C.sec,
          }}>{l}</button>
        ))}
      </div>

      <svg viewBox={`-0.5 -0.5 ${CW + 1} ${CD + 1}`} role="img"
           aria-label={`Shot zone map for ${p.name}`}
           style={{ width: "100%", display: "block", background: C.visual, border: `1px solid ${C.border}` }}>
        {/* fills painted back to front — overlap does the clipping */}
        <rect x={0} y={0} width={CW} height={CD} fill={tone(4).c} fillOpacity={tone(4).o} />
        <rect x={0} y={sy(CORNER_MEET)} width={CORNER_X} height={CORNER_MEET} fill={tone(3).c} fillOpacity={tone(3).o} />
        <rect x={CW - CORNER_X} y={sy(CORNER_MEET)} width={CORNER_X} height={CORNER_MEET} fill={tone(3).c} fillOpacity={tone(3).o} />
        <path d={`${ARC_D} L ${CW - CORNER_X} ${CD} L ${CORNER_X} ${CD} Z`} fill={tone(2).c} fillOpacity={tone(2).o} />
        <rect x={CW / 2 - 8} y={sy(19)} width={16} height={19} fill={tone(1).c} fillOpacity={tone(1).o} />
        <path d={`M ${CW / 2 - RA_R} ${CD} L ${CW / 2 - RA_R} ${sy(HOOP_Y)} A ${RA_R} ${RA_R} 0 0 1 ${CW / 2 + RA_R} ${sy(HOOP_Y)} L ${CW / 2 + RA_R} ${CD} Z`}
              fill={tone(0).c} fillOpacity={tone(0).o} />

        {/* court markings */}
        <g fill="none" stroke={C.text} strokeWidth={0.2} strokeOpacity={0.55} strokeLinejoin="round">
          <rect x={0} y={0} width={CW} height={CD} strokeOpacity={0.3} />
          <rect x={CW / 2 - 8} y={sy(19)} width={16} height={19} />
          <path d={`M ${CW / 2 - 6} ${sy(19)} A 6 6 0 0 1 ${CW / 2 + 6} ${sy(19)}`} />
          <path d={ARC_D} />
          <line x1={CORNER_X} y1={CD} x2={CORNER_X} y2={sy(CORNER_MEET)} />
          <line x1={CW - CORNER_X} y1={CD} x2={CW - CORNER_X} y2={sy(CORNER_MEET)} />
          <path d={`M ${CW / 2 - RA_R} ${sy(HOOP_Y)} A ${RA_R} ${RA_R} 0 0 1 ${CW / 2 + RA_R} ${sy(HOOP_Y)}`} strokeOpacity={0.35} />
        </g>
        <line x1={CW / 2 - 3} y1={sy(4)} x2={CW / 2 + 3} y2={sy(4)} stroke={C.text} strokeWidth={0.4} strokeOpacity={0.7} />
        <circle cx={CW / 2} cy={sy(HOOP_Y)} r={0.7} fill="none" stroke={C.accent} strokeWidth={0.38} />

        {/* labels — positions checked against each zone's real free space */}
        <ZoneLabel x={CW / 2} y={sy(3.3)} name="RIM"       value={val(0)} delta={dlt(0)} mode="freq" />
        <ZoneLabel x={CW / 2} y={sy(15.4)} name="PAINT"     value={val(1)} delta={dlt(1)} mode={mode} />
        <ZoneLabel x={CW / 2} y={sy(24.2)} name="MID-RANGE" value={val(2)} delta={dlt(2)} mode={mode} />
        <ZoneLabel x={CW / 2} y={sy(32.4)} name="ABOVE THE BREAK" value={val(4)} delta={dlt(4)} mode={mode} />
        {/* Corner: ONE label, single rotated line. Both corners are one combined
            zone, so a second figure would only invite the reader to think they
            differ. Two stacked lines can't work rotated — they'd spread across
            the corner's 3ft width instead of down its 7.8ft height, which is
            what pushed the right-hand label off the canvas. */}
        {val(3) != null && (
          <text x={CORNER_X / 2} y={sy(4.0)} textAnchor="middle"
                transform={`rotate(-90 ${CORNER_X / 2} ${sy(4.0)})`} {...HALO}
                style={{ fontFamily: DISPLAY, fontSize: 2.4, fontWeight: 700, fill: C.text }}>
            {val(3).toFixed(1)}%
          </text>
        )}
        {/* rim delta sits beside the arc rather than under it — no room below */}
        {mode === "eff" && dlt(0) != null && (
          <text x={CW / 2} y={sy(10.6)} textAnchor="middle" {...HALO}
                style={{ fontSize: 1.5, fontWeight: 700, fill: dlt(0) > 0 ? C.good : C.bad }}>
            {dlt(0) > 0 ? "+" : ""}{dlt(0).toFixed(1)} vs lg
          </text>
        )}
      </svg>

      <div style={{ display: "flex", justifyContent: "space-between", gap: 10, fontSize: 9, color: C.mute, padding: "7px 0 0", lineHeight: 1.5 }}>
        <span>
          {mode === "freq"
            ? `Share of ${d.n} field goal attempts. Free throws excluded. Darker = more shots.`
            : `Field goal % by zone. Green beats the league in that zone, red trails it.`}
        </span>
        <span style={{ whiteSpace: "nowrap", ...agate }}>{d.n} FGA</span>
      </div>
      <div style={{ fontSize: 9, color: C.mute, paddingTop: 3, lineHeight: 1.5 }}>
        The rotated figure in the corner is <b style={{ color: C.text }}>Corner 3</b> — both corners combined, which is why only one is marked. Attempts by zone:{" "}
        {["rim", "paint", "mid", "corner", "above"].map((z, i) => `${z} ${d.a[i]}`).join(" · ")}.
        {d.p.some(x => x == null) && " Zones under 8 attempts are greyed — too few to judge."}
      </div>

      {d.c && <>
        <SectionHead action="vs league">How the shots come</SectionHead>
        {[["spot", "Catch & shoot"], ["drive", "Driving"], ["offdrib", "Off the dribble"],
          ["cut", "Cutting"], ["post", "Post up / turnaround"], ["putback", "Putback"]].map(([k, l], i) => {
          const v = d.c[i], lg = SHOTS.LG.create[i], delta = v - lg;
          return (
            <div key={k} style={{ padding: "8px 0", borderBottom: `1px solid ${C.border}` }}>
              <div style={{ display: "flex", justifyContent: "space-between", alignItems: "baseline", marginBottom: 3 }}>
                <span style={{ fontSize: 11.5, color: C.sec }}>{l}</span>
                <span style={{ ...agate, fontSize: 11.5 }}>
                  <b>{v.toFixed(1)}%</b>
                  <span style={{ color: Math.abs(delta) < 3 ? C.mute : delta > 0 ? C.good : C.bad, marginLeft: 6, fontWeight: 700 }}>
                    {delta >= 0 ? "+" : ""}{delta.toFixed(1)}
                  </span>
                </span>
              </div>
              <div style={{ height: 6, background: C.border, position: "relative" }}>
                <div style={{ height: "100%", width: `${Math.min(v / 50 * 100, 100)}%`, background: C.blue }} />
                {/* league tick — the bar without it is just the number written twice */}
                <div style={{ position: "absolute", left: `${Math.min(lg / 50 * 100, 100)}%`, top: -2, bottom: -2, width: 1.5, background: C.rule }} />
              </div>
            </div>
          );
        })}
        <div style={{ fontSize: 9, color: C.mute, paddingTop: 7, lineHeight: 1.5 }}>
          Tick marks the league average. Derived from play type — a “driving layup” counts as driving, a “step back jump shot” as off the dribble.
        </div>
      </>}
    </>
  );
}

function TabBar({ tab, setTab }) {
  const items = [["home", Home, "Today"], ["teams", Shield, "Teams"], ["players", Users, "Players"], ["schedule", CalendarDays, "Schedule"], ["more", MoreHorizontal, "About"]];
  return (
    <div style={{ display: "flex", borderTop: `1px solid ${C.border}`, background: C.visual, padding: "6px 0 12px", flexShrink: 0 }}>
      {items.map(([k, Icon, label]) => (
        <button key={k} onClick={() => setTab(k)} style={{ flex: 1, border: "none", background: "none", display: "flex", flexDirection: "column", alignItems: "center", gap: 3, padding: "3px 0", cursor: "pointer" }}>
          <Icon size={19} color={tab === k ? C.accent : C.mute} strokeWidth={tab === k ? 2.4 : 1.7} />
          <span style={{ fontSize: 9, fontWeight: tab === k ? 700 : 500, color: tab === k ? C.accent : C.mute, letterSpacing: .4 }}>{label}</span>
        </button>
      ))}
    </div>
  );
}
